### ISSUE TITLE
[FEAT] 운동 기록 저장/조회

### ISSUE THREAD

**Issue by hagoeun0119** [BeyondVision-NalBao/BeyondVision-Server#6]
## 📄 DESCRIPTION
- 운동 기록 전체 조회
- 운동 기록 저장
- 카테고리별 운동 종류 상세 조회

## ✅ TODO
- [x] 최대 3개월 기록 조회
- [x] 운동 종류, 횟수, 시간 저장
- [x] 운동 기록 3개월 조회 테스트
- [x] 카테고리별 운동 종류 상세 조회 테스트
